FROM ollama/ollama:latest

# Création du répertoire pour les modèles
RUN mkdir -p /root/.ollama

# Copie du script d'entrée
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Exposition du port
EXPOSE 11434

# Définition du point d'entrée
ENTRYPOINT ["/entrypoint.sh"]